### ISSUE TITLE
Access denied attempting to index any directory, no matter if running in administrator mode

### ISSUE THREAD

**Issue by Kaleidio** [overwolf/jar-infection-scanner#1]
![image](https://github.com/overwolf/jar-infection-scanner/assets/82226641/5cf4a8ca-e831-44fc-a09e-dbe01cd31c26)

**Comment by Kaleidio** [comment]
Windows 10 21H2

**Comment by TheOriginalGolem** [comment]
Same issue

**Comment by NighthowlerStudios** [comment]
closing as it seems the application is only built to handle modpacks
